CREATE table product(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ten VARCHAR (100) NOT NULL ,
giatien VARCHAR (255) NOT NULL ,
tonkho VARCHAR (255)NOT NULL ,
nhacungcap VARCHAR (255) NOT NULL,
ngaytao DATE NOT NULL
);
